services:
  triptip_service:
    image: cosmosfactory/triptip_backend:latest
    container_name: triptip_service
    command: >
      bash -c "poetry run alembic upgrade head &&
      poetry run uvicorn src.main:app --forwarded-allow-ips='*' --proxy-headers --host 0.0.0.0 --port 8000 --workers 4"
    depends_on:
      - db
    restart: always
    env_file:
      - .env

  db:
    image: postgres:16.2-alpine3.18
    container_name: triptip_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - ${DB_PORT}

  triptip_frontend:
    image: cosmosfactory/triptip_frontend:latest
    container_name: triptip_frontend
    restart: always

  nginx:
    image: cosmosfactory/triptip_frontend:latest
    container_name: triptip_nginx
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - triptip_service
      - triptip_frontend
    restart: always

volumes:
  postgres_data:
