services:
  triptip_service:
    image: cosmosfactory/triptip_backend:latest
    container_name: triptip_service
    command: poetry run gunicorn src.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    depends_on:
      - db
    restart: always
    env_file:
      - .env

  db:
    image: postgres:16.2-alpine3.18
    container_name: triptip_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - ${DB_PORT}

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.nginx
    container_name: triptip_nginx
    volumes: 
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - triptip_service
    restart: always

volumes:
  postgres_data:
