version: '3.8'

services:
  triptip_service:
    build: .
    command: poetry run uvicorn src.main:app --forwarded-allow-ips='*' --proxy-headers --host 0.0.0.0 --port 8000 --workers 4
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
    env_file:
      - .env

  db:
    image: postgres:16.2-alpine3.18
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - ${DB_PORT}

volumes:
  postgres_data:
