[tool.logfire]
pydantic_plugin_record = "all"
[project]
authors = [
    {name = "Nikita Assorov"},
]
requires-python = "<4.0,>=3.12"
dependencies = [
    "fastapi<1.0.0,>=0.110.0",
    "uvicorn[standard]<1.0.0,>=0.30.1",
    "ruff<1.0.0,>=0.3.4",
    "pydantic-settings<3.0.0,>=2.2.1",
    "sqlalchemy<3.0.0,>=2.0.29",
    "asyncpg<1.0.0,>=0.29.0",
    "alembic<2.0.0,>=1.13.1",
    "gunicorn<23.0.0,>=22.0.0",
    "pre-commit<4.0.0,>=3.7.0",
    "pytest<9.0.0,>=8.1.1",
    "pytest-asyncio<1.0.0,>=0.23.6",
    "httpx<1.0.0,>=0.27.0",
    "pytest-cov<6.0.0,>=5.0.0",
    "coverage<8.0.0,>=7.4.4",
    "factory-boy<4.0.0,>=3.3.0",
    "itsdangerous<3.0.0,>=2.2.0",
    "pydantic[email]<3.0.0,>=2.7.1",
    "bcrypt<5.0.0,>=4.0.1",
    "passlib[bcrypt]<2.0.0,>=1.7.4",
    "python-jose[cryptography]<4.0.0,>=3.3.0",
    "python-multipart<1.0.0,>=0.0.18",
    "sentry-sdk[fastapi]<3.0.0,>=2.8.0",
    "aiosqlite<1.0.0,>=0.20.0",
    "sqladmin<1.0.0,>=0.17.0",
    "aioboto3<14.0.0,>=13.1.1",
    "moto<6.0.0,>=5.0.16",
    "logfire[fastapi]>=3.14.1",
    "aiosmtplib>=4.0.0",
    "pyjwt>=2.10.1",
]
name = "triptip-backend"
version = "0.1.0"
description = ""
readme = "README.md"


[tool.ruff]
line-length = 100

[tool.ruff.lint]
extend-select = ["I", "W", "B", "I",]
exclude = ["src/migrations/*.py",]

[tool.flake8]
max-line-length = 100
ignore = ["B008"]
exclude = ["src/migrations/*.py",]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
asyncio_mode = "auto"
python_files = ["*_test.py", "*_tests.py", "test_*.py"]
addopts = "-vv -p no:cacheprovider"

[tool.ruff.lint.flake8-bugbear]
# Allow default arguments like, e.g., `data: List[str] = fastapi.Query(None)`.
extend-immutable-calls = ["fastapi.Depends", "fastapi.Query"]

