"""empty message

Revision ID: 55b8a99fe85c
Revises: 1006ec379732
Create Date: 2025-09-13 11:57:53.360842

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "55b8a99fe85c"
down_revision: Union[str, None] = "1006ec379732"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trips", sa.Column("likes_counter", sa.Integer(), nullable=False))
    op.add_column("users", sa.Column("followings_counter", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "followings_counter")
    op.drop_column("trips", "likes_counter")
    # ### end Alembic commands ###
