"""empty message

Revision ID: 1ec81612877f
Revises: 47e401fddfdf
Create Date: 2025-11-11 23:07:13.887896

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1ec81612877f"
down_revision: Union[str, None] = "47e401fddfdf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    visibility_enum = sa.Enum("DRAFT", "PUBLISHED", "PRIVATE", name="visibilityenum")

    visibility_enum.create(op.get_bind(), checkfirst=True)  # Create the enum type in the database

    op.add_column(
        "trips",
        sa.Column(
            "visibility",
            visibility_enum,
            nullable=False,
            server_default="DRAFT",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trips", "visibility")
    # ### end Alembic commands ###
