"""empty message

Revision ID: 857f7d72faee
Revises: c4ebe6d755ee
Create Date: 2025-04-25 18:45:54.767752

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "857f7d72faee"
down_revision: Union[str, None] = "c4ebe6d755ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("locations", sa.Column("sequence_id", sa.Integer(), nullable=False))
    op.create_unique_constraint("_trip_sequence_uc", "locations", ["trip_id", "sequence_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_trip_sequence_uc", "locations", type_="unique")
    op.drop_column("locations", "sequence_id")
    # ### end Alembic commands ###
