"""empty message

Revision ID: c01f01e0df56
Revises: 857f7d72faee
Create Date: 2025-04-26 13:27:02.179067

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c01f01e0df56"
down_revision: Union[str, None] = "857f7d72faee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("locations", "sequence_id", existing_type=sa.INTEGER(), nullable=False)
    op.add_column(
        "users",
        sa.Column("is_verified", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_verified")
    op.alter_column("locations", "sequence_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
