"""empty message

Revision ID: 47e401fddfdf
Revises: 55b8a99fe85c
Create Date: 2025-10-27 21:14:59.441192

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "47e401fddfdf"
down_revision: Union[str, None] = "55b8a99fe85c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comments", sa.Column("deleted", sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column(
        "emails", sa.Column("deleted", sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column(
        "highlights", sa.Column("deleted", sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column(
        "likes", sa.Column("deleted", sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column(
        "locations", sa.Column("deleted", sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column(
        "refresh_tokens",
        sa.Column("deleted", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "routes", sa.Column("deleted", sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column(
        "subscriptions",
        sa.Column("deleted", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "trips", sa.Column("deleted", sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column(
        "users", sa.Column("deleted", sa.Boolean(), nullable=False, server_default=sa.false())
    )

    # Drop server defaults after backfilling existing rows
    op.alter_column("comments", "deleted", server_default=None)
    op.alter_column("emails", "deleted", server_default=None)
    op.alter_column("highlights", "deleted", server_default=None)
    op.alter_column("likes", "deleted", server_default=None)
    op.alter_column("locations", "deleted", server_default=None)
    op.alter_column("refresh_tokens", "deleted", server_default=None)
    op.alter_column("routes", "deleted", server_default=None)
    op.alter_column("subscriptions", "deleted", server_default=None)
    op.alter_column("trips", "deleted", server_default=None)
    op.alter_column("users", "deleted", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "deleted")
    op.drop_column("trips", "deleted")
    op.drop_column("subscriptions", "deleted")
    op.drop_column("routes", "deleted")
    op.drop_column("refresh_tokens", "deleted")
    op.drop_column("locations", "deleted")
    op.drop_column("likes", "deleted")
    op.drop_column("highlights", "deleted")
    op.drop_column("emails", "deleted")
    op.drop_column("comments", "deleted")
    # ### end Alembic commands ###
