"""empty message

Revision ID: c4ebe6d755ee
Revises: 3ebe25df6271
Create Date: 2025-04-13 16:08:43.231297

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c4ebe6d755ee"
down_revision: Union[str, None] = "3ebe25df6271"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("routes", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("routes", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
