"""empty message

Revision ID: 3ebe25df6271
Revises: 0b163071ed38
Create Date: 2025-04-13 13:02:20.477064

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3ebe25df6271"
down_revision: Union[str, None] = "0b163071ed38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("routes", "destination_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("routes", "destination_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
