"""20240725130847

Revision ID: 852568712470
Revises: e864760649c8
Create Date: 2024-07-25 13:08:48.594401

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "852568712470"
down_revision: Union[str, None] = "e864760649c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_admin", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###

    # Manually add the operations to update the foreign key constraint
    op.drop_constraint("refresh_tokens_user_id_fkey", "refresh_tokens", type_="foreignkey")
    op.create_foreign_key(
        "refresh_tokens_user_id_fkey",
        "refresh_tokens",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # Add a comment to indicate the change in cascade options for the trips relationship
    # Note: This change affects ORM behavior and doesn't require a database schema change
    # Cascade options for trips relationship updated to "save-update, merge"


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_admin", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###

    # Manually reverse the foreign key constraint change
    op.drop_constraint("refresh_tokens_user_id_fkey", "refresh_tokens", type_="foreignkey")
    op.create_foreign_key(
        "refresh_tokens_user_id_fkey", "refresh_tokens", "users", ["user_id"], ["id"]
    )

    # Note: Reverse the ORM-level change for cascade options if necessary
    # Cascade options for trips relationship will be reverted to their previous state if needed
