"""20240813133934

Revision ID: b8facb845b7f
Revises: fb40e8d83b0a
Create Date: 2024-08-13 13:39:35.043522

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b8facb845b7f"
down_revision: Union[str, None] = "fb40e8d83b0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add the column as nullable
    op.add_column("routes", sa.Column("author_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "routes", "users", ["author_id"], ["id"])

    # Step 2: Populate existing rows with author_id = 1
    op.execute("UPDATE routes SET author_id = 1")

    # Step 3: Alter the column to be NOT NULL
    op.alter_column("routes", "author_id", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "routes", type_="foreignkey")
    op.drop_column("routes", "author_id")
    # ### end Alembic commands ###
