FROM nginx:1.24.0
RUN rm /etc/nginx/conf.d/default.conf
RUN apt-get update && apt-get install -y python3-pip
RUN pip3 install certbot-nginx
RUN mkdir -p /etc/letsencrypt/live/
COPY nginx/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]