name: Telegram Notification
run-name: Telegram notification of ${{ github.ref_name }} by @${{ github.actor }}

on:
    workflow_run:
        workflows: [CD]
        types: [completed]
        branches: [dev]
    pull_request:
        branches: [dev]

permissions:
    statuses: write

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download coverage report
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: ci.yml
          commit: ${{ github.event.workflow_run.head_sha }}

      - name: Read Coverage Data
        id: coverage
        run: |
          coverage_percentage=$(cat coverage-report/status.json | jq -r '.coverage')
          echo "::set-output name=coverage::$coverage_percentage"

      - name: Send Telegram message on successful deploy
        if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚀 Deploy to prod was successful!
            - Workflow: ${{ github.workflow }}
            - Run ID: ${{ github.run_id }}
            - Commit: ${{ github.sha }}
            - Test coverage: ${{ steps.coverage.outputs.coverage }}

      - name: Send Telegram message on PR opened
        if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            📬 A new PR was opened to the dev branch!
            - PR: #${{ github.event.pull_request.number }}
            - Title: ${{ github.event.pull_request.title }}
            - Author: ${{ github.event.pull_request.user.login }}